# @package _global_
defaults:
  - sine/default_sine

dataset:
  data_dir: dataloaders/data/basic_waveforms/sine_200hz_small.npy
  min_freq: 200
  max_freq: 200
  num_frequencies: 1
  num_random_amplitudes: 20
  noise_amplitude: 0.1
